### ISSUE TITLE
Not an Issue: Question

### ISSUE THREAD

**Issue by TophC7** [nomad23541/lightdm-webkit-simply-theme#1]
Hi, I know this is probably a personal project but it's actually the only webkit2-greeter theme I have liked so far. So my question is if you have planned to add more features to the theme? I'd make a theme myself but well i dont know how.. thanks!

**Comment by nomad23541** [comment]
Hi TophC7, thanks for liking it! Unfortunately I don't plan on adding any features to this project, as it has everything that I need. 

You can replace the background by placing your own image in /img/ and renaming to to background.jpg. And to change the window manager that lightdm will direct you to after login, edit the session line in index.theme.

If you know HTML, CSS, and Javascript, you could easily create your own theme, as lightdm-webkit uses these. All I did was modify the HTML and CSS from this [repo](https://github.com/victorhaggqvist/lightdm-webkit-archsingle-theme).

**Comment by TophC7** [comment]
I did my own edit of this theme of yours hope you dont mind! 
https://github.com/TophC7/Enkel.git

**Comment by nomad23541** [comment]
I don't mind at all! Looks sweet! :smile:
